
-- lkpClass_Names
INSERT INTO [lkpClass_Names]([Class_Name_Description]) VALUES ('Please Select...')
INSERT INTO [lkpClass_Names]([Class_Name_Description]) VALUES ('NFC')
INSERT INTO [lkpClass_Names]([Class_Name_Description]) VALUES ('Pre-Beginner Dog')
INSERT INTO [lkpClass_Names]([Class_Name_Description]) VALUES ('Pre-Beginner Bitch')
INSERT INTO [lkpClass_Names]([Class_Name_Description]) VALUES ('Pre-Beginner Dog & Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Beginner Dog')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Beginner Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Beginner Dog & Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Novice Dog')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Novice Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Novice Dog & Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('A Dog')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('A Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('A Dog & Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('B Dog')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('B Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('B Dog & Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('C Dog')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('C Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('C Dog & Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Championship C Dog')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Championship C Bitch')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Introductory')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Multi-Choice')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('YKC Starters')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('YKC Elementary')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('YKC Graduate')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('YKC Intermediate')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('YKC Advanced')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Kennel Club Good Citizen Scheme Special Pre-Beginner Stakes')
INSERT INTO [lkpClass_Names] ([Class_Name_Description]) VALUES ('Special Class')


-- lkpDog_Breeds
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Please Select...')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Affenpinscher')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Afghan Hound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Airedale Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Alaskan Malamute')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('American Cocker Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Anatolian Shepherd Dog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Australian Shepherd')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Australian Silky Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Australian Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Basenji')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Basset Griffon Vendeen (Petit)')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Basset Hound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('BC')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Beagle')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Bearded Collie')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Bedlington Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Bernese Mountain Dog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Bichon Frise')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Bloodhound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Border Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Borzoi')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Boston Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Bouvier Des Flandres')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Boxer')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Briard')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Brittany')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('BSD')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Bull Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Bulldog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Bullmastiff')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Cairn Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Canaan Dog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Cavalier King Charles Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Cesky Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Chesapeake Bay Retriever')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Chihuahua')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Chinese Crested')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Chow Chow')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Clumber Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Cocker Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Collie (Rough)')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Collie (Smooth)')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Curly Coated Retriever')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Dachshund')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Dalmatian')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Dandie Dinmont Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Deerhound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Dobermann')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Elkhound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('English Setter')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('English Springer Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('English Toy Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Estrela Mountain Dog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Field Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Finnish Spitz')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Flat Coated Retriever')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Fox Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Foxhound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('French Bulldog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('German Pinscher')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('German Short Haired Pointer')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('German Spitz')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('German Wire Haired Pointer')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Giant Schnauzer')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Glen of Imaal Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Golden Retriever')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Gordon Setter')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Great Dane')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Greenland Dog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Greyhound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Griffon Bruxellois')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('GSD')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Hamiltonstovare')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Havanese')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Hovawart')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Hungarian Vizsla')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Hungarian Wire Haired Vizsla')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Ibizan Hound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Irish Red & White Setter')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Irish Setter')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Irish Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Irish Water Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Irish Wolfhound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Italian Greyhound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Italian Spinone')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Jack Russell Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Japanese Akita')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Japanese Chin')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Japanese Shiba Inu')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Japanese Spitz')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Keeshond')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Kerry Blue Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('King Charles Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Komondor')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Kooikerhondje')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Labrador Retriever')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Lakeland Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Lancashire Heeler')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Large Munsterlander')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Leonberger')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Lhasa Apso')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Lowchen')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Lurcher')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Maltese')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Manchester Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Maremma Sheepdog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Mastiff')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Miniature Poodle')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Miniature Schnauzer')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Neapolitan Mastiff')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Newfoundland')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Norfolk Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Norwegian Buhund')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Norwich Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Nova Scotia Duck Tolling Retriever')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Old English Sheepdog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Otterhound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Papillon')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Parson Jack Russell Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Pekingese')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Pembrokeshire Corgi')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Pharaoh Hound')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Pointer')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Polish Lowland Sheepdog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Pomeranian')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Portuguese Water Dog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Pug')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Pyrenean Mountain Dog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Pyrenean Sheepdog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Rhodesian Ridgeback')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Rottweiler')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Russian Black Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Saluki')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Samoyed')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Schipperke')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Schnauzer')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Scottish Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Sealyham Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Shar Pei')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Shetland Sheepdog')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Shih Tzu')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Siberian Husky')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Skye Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Sloughi')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Soft Coated Wheaten Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('St Bernard')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Staffordshire Bull Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Standard Poodle')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Sussex Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Swedish Vallhund')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Tibetan Mastiff')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Tibetan Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Tibetan Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Toy Poodle')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Weimaraner')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Welsh Corgi')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Welsh Springer Spaniel')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Welsh Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('West Highland White Terrier')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Whippet')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('WS')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('XB')
INSERT INTO [lkpDog_Breeds] ([Dog_Breed_Description]) VALUES ('Yorkshire Terrier')


-- lkpDog_Gender
INSERT INTO [lkpDog_Gender] ([Dog_Gender]) VALUES ('Please Select...')
INSERT INTO [lkpDog_Gender] ([Dog_Gender]) VALUES ('Dog')
INSERT INTO [lkpDog_Gender] ([Dog_Gender])VALUES ('Bitch')


-- lkpShow_Roles
INSERT INTO [lkpShow_Roles] ([Show_Role_Description]) VALUES ('Please Select...')
INSERT INTO [lkpShow_Roles] ([Show_Role_Description]) VALUES ('Chief Steward')
INSERT INTO [lkpShow_Roles] ([Show_Role_Description]) VALUES ('Chief Stay Steward')
INSERT INTO [lkpShow_Roles] ([Show_Role_Description]) VALUES ('Show Manager')


-- lkpShow_Types
INSERT INTO [lkpShow_Types] ([Show_Type_Description]) VALUES ('Please Select...')
INSERT INTO [lkpShow_Types] ([Show_Type_Description]) VALUES ('Open')
INSERT INTO [lkpShow_Types] ([Show_Type_Description]) VALUES ('Championship')
INSERT INTO [lkpShow_Types] ([Show_Type_Description]) VALUES ('Limit')
INSERT INTO [lkpShow_Types] ([Show_Type_Description]) VALUES ('Heelwork to Music')


-- lkpShow_Years
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2012)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2013)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2014)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2015)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2016)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2017)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2018)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2019)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2020)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2021)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2022)
INSERT INTO [lkpShow_Years] ([Show_Year]) VALUES (2023)



INSERT INTO dbo.aspnet_SchemaVersions 
VALUES
('common', 1, 1),
('health monitoring', 1, 1),
('membership', 1, 1),
('personalization', 1, 1),
('profile', 1, 1),
('role manager', 1, 1);
GO
